#!/usr/bin/env bash
# ============================================================================
# Agent Fleet — one-command bootstrap (solo / single-machine, localhost).
#
#   git clone <repo> agent-fleet && cd agent-fleet && ./install.sh
#
# Idempotent (safe to re-run). Sets up a fresh machine end-to-end: tokens, the
# self-contained MCP config, the Claude Code hooks, builds + starts the hub, and
# verifies it. Multi-node (Tailscale / Cloudflare / tmux) is opt-in — see
# QUICKSTART.md. No secrets are hardcoded; tokens are generated locally.
#
# Flags:
#   --no-start   set everything up but do not launch the hub
#   --port N     hub port (default: PORT env / .env / 9559)
# ============================================================================
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$REPO_ROOT"

# ---- pretty output --------------------------------------------------------
if [ -t 1 ]; then
  C_G=$'\033[1;32m'; C_Y=$'\033[1;33m'; C_R=$'\033[1;31m'; C_B=$'\033[1;34m'; C_0=$'\033[0m'
else
  C_G=""; C_Y=""; C_R=""; C_B=""; C_0=""
fi
log()  { printf '%s[fleet]%s %s\n' "$C_G" "$C_0" "$*"; }
info() { printf '%s[fleet]%s %s\n' "$C_B" "$C_0" "$*"; }
warn() { printf '%s[fleet]%s %s\n' "$C_Y" "$C_0" "$*" >&2; }
die()  { printf '%s[fleet] error:%s %s\n' "$C_R" "$C_0" "$*" >&2; exit 1; }

# ---- flags ----------------------------------------------------------------
START_HUB=1
PORT_OVERRIDE=""
while [ $# -gt 0 ]; do
  case "$1" in
    --no-start) START_HUB=0 ;;
    --port) shift; PORT_OVERRIDE="${1:-}" ;;
    -h|--help) grep '^#' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) die "unknown flag: $1 (try --help)" ;;
  esac
  shift
done

# ---- 1. Node preflight ----------------------------------------------------
# The hub's better-sqlite3 is compiled for Node 22's ABI; any other major crashes
# it. Reuse the repo's own preflight so the message + pin stay single-sourced.
command -v node >/dev/null 2>&1 || die "Node.js not found. Install Node 22 (see .nvmrc), then re-run."
if [ -f scripts/check-node.mjs ]; then
  node scripts/check-node.mjs || die "Wrong Node version. Run: nvm install && nvm use (Node 22 per .nvmrc), then re-run ./install.sh"
else
  node_major="$(node -p 'process.versions.node.split(".")[0]')"
  [ "$node_major" -ge 22 ] || die "Node >= 22 required (found $(node -v)); better-sqlite3 needs Node 22's ABI."
fi
log "Node $(node -v) OK"

# ---- 2. .env (tokens + solo defaults), idempotent -------------------------
ENV_FILE="$REPO_ROOT/.env"
gen_token() { node -e 'process.stdout.write(require("crypto").randomBytes(24).toString("hex"))'; }
env_port="${PORT_OVERRIDE:-${PORT:-9559}}"
if [ -f "$ENV_FILE" ]; then
  log ".env already exists — keeping it (re-run safe; delete it to regenerate tokens)."
else
  log "Generating .env (fresh tokens + solo localhost defaults)…"
  mkdir -p "$REPO_ROOT/data"
  join_token="$(gen_token)"
  admin_token="$(gen_token)"
  umask 077
  cat > "$ENV_FILE" <<ENV
# Generated by install.sh — solo / localhost. NEVER commit this file.
# Multi-node opts in here (set AGENT_FLEET_HUB_URL / CF_ACCESS_* — see .env.example).
AGENT_FLEET_JOIN_TOKEN=$join_token
AGENT_FLEET_ADMIN_TOKEN=$admin_token
PORT=$env_port
AGENT_FLEET_HUB_URL=http://localhost:$env_port
AGENT_FLEET_DB_PATH=$REPO_ROOT/data/agent-fleet.db
AF_OPERATOR_NAME=Operator
ENV
  chmod 600 "$ENV_FILE"
fi

# Load .env into this shell (export every assignment).
set -a; # shellcheck disable=SC1090
. "$ENV_FILE"; set +a
[ -n "${PORT_OVERRIDE}" ] && PORT="$PORT_OVERRIDE"
PORT="${PORT:-9559}"
HUB_URL="${AGENT_FLEET_HUB_URL:-http://localhost:$PORT}"
[ -n "${AGENT_FLEET_JOIN_TOKEN:-}" ] || die ".env is missing AGENT_FLEET_JOIN_TOKEN"
[ -n "${AGENT_FLEET_ADMIN_TOKEN:-}" ] || die ".env is missing AGENT_FLEET_ADMIN_TOKEN"

# ---- 3. Dependencies ------------------------------------------------------
log "Installing dependencies (npm install)…"
npm install --no-audit --no-fund

# ---- 3b. Guarantee the better-sqlite3 native binary loads ------------------
# The hub require()s better-sqlite3's compiled .node at runtime. This guard is a
# no-op on Linux/macOS (the binary loads after a normal install — matrix-proven
# on npm 10 and 11), but it makes failure LOUD instead of a cryptic hub crash:
# verify the load from the hub's own resolution context; if it fails, rebuild
# explicitly and re-verify; if it still fails, die with guidance. (npm 11.16+'s
# allow-scripts warning is advisory — scripts still run — so it is not the cause;
# we gate on whether the binary actually LOADS.)
loads_native() { ( cd "$REPO_ROOT/hub" && node -e 'require("better-sqlite3")' ) >/dev/null 2>&1; }
if loads_native; then
  log "Native deps OK (better-sqlite3 loads)."
else
  warn "better-sqlite3 did not load after npm install — rebuilding native deps (better-sqlite3, node-pty)…"
  npm rebuild better-sqlite3 node-pty --foreground-scripts || true
  if loads_native; then
    log "Native deps rebuilt (better-sqlite3 loads)."
  else
    die "better-sqlite3's native binary is missing/unloadable after npm install + npm rebuild. Inspect the rebuild output above (prebuild-install / node-gyp), then re-run ./install.sh"
  fi
fi

# ---- 4. Build hub + MCP bundle -------------------------------------------
log "Building hub + MCP bundle…"
npm run build
npm run bundle

# ---- 5. Vendored, self-contained MCP config (no marketplace round-trip) ----
# Claude Code loads project-level .mcp.json. Point it straight at the committed
# bundle so `git clone` has everything. The marketplace plugin remains an
# optional alternative (see QUICKSTART.md).
MCP_BUNDLE="$REPO_ROOT/plugin/dist/mcp-server.mjs"
[ -f "$MCP_BUNDLE" ] || die "MCP bundle missing at $MCP_BUNDLE (npm run bundle should have built it)."
log "Writing vendored MCP config → .mcp.json"
MCP_BUNDLE="$MCP_BUNDLE" AGENT_FLEET_JOIN_TOKEN="$AGENT_FLEET_JOIN_TOKEN" AGENT_FLEET_HUB_URL="$HUB_URL" \
REPO_ROOT="$REPO_ROOT" node <<'NODE'
const fs = require("fs"), path = require("path");
const p = process.env;
const out = path.join(p.REPO_ROOT, ".mcp.json");
let cfg = {};
try { cfg = JSON.parse(fs.readFileSync(out, "utf8")); } catch { cfg = {}; }
cfg.mcpServers = cfg.mcpServers || {};
cfg.mcpServers["agent-fleet"] = {
  command: "node",
  args: [p.MCP_BUNDLE],
  env: { AGENT_FLEET_JOIN_TOKEN: p.AGENT_FLEET_JOIN_TOKEN, AGENT_FLEET_HUB_URL: p.AGENT_FLEET_HUB_URL },
};
fs.writeFileSync(out, JSON.stringify(cfg, null, 2) + "\n");
NODE

# ---- 6. Claude Code hooks: copy + wire settings.json ----------------------
CLAUDE_HOME="${CLAUDE_CONFIG_DIR:-$HOME/.claude}"
HOOKS_DIR="$CLAUDE_HOME/hooks"
SETTINGS="$CLAUDE_HOME/settings.json"
mkdir -p "$HOOKS_DIR/state"

FLEET_HOOKS=(
  agent-fleet-sessionstart.sh
  agent-fleet-msgcheck.sh
  agent-fleet-rewake.sh
  agent-fleet-tabtitle.sh
  fleet-taskboard.js
  fleet-plan-heartbeat.js
  wt-lease-guard.js
  wt-context-gauge.cjs
)
log "Installing ${#FLEET_HOOKS[@]} hooks → $HOOKS_DIR"
for h in "${FLEET_HOOKS[@]}"; do
  src="$REPO_ROOT/deploy/hooks/$h"
  [ -f "$src" ] || die "hook source missing: $src"
  cp "$src" "$HOOKS_DIR/$h"
  chmod +x "$HOOKS_DIR/$h"
done

# Merge the canonical fleet wiring into settings.json (preserve existing
# non-fleet hooks; idempotent — fleet entries are replaced, not duplicated).
log "Wiring hooks into $SETTINGS (merge, non-destructive)…"
FLEET_SETTINGS="$SETTINGS" FLEET_HOOKS_DIR="$HOOKS_DIR" \
FLEET_JOIN_TOKEN="$AGENT_FLEET_JOIN_TOKEN" FLEET_HUB_URL="$HUB_URL" FLEET_PLATFORM=posix \
node "$REPO_ROOT/scripts/install/wire-fleet-hooks.mjs"

# ---- 7. Start the hub + verify -------------------------------------------
verify_board() {
  for _ in $(seq 1 30); do
    code="$(curl -s -o /dev/null -w '%{http_code}' "http://localhost:$PORT/board" 2>/dev/null || true)"
    [ "$code" = "200" ] && return 0
    sleep 0.5
  done
  return 1
}

if [ "$START_HUB" -eq 1 ]; then
  if curl -s -o /dev/null "http://localhost:$PORT/board" 2>/dev/null; then
    warn "Something is already serving port $PORT — not starting a second hub. (Use --port N or stop it.)"
  else
    mkdir -p "$REPO_ROOT/logs"
    log "Starting the hub on port $PORT (background)…"
    PORT="$PORT" nohup npm start --silent >"$REPO_ROOT/logs/hub.log" 2>&1 &
    echo $! > "$REPO_ROOT/.hub.pid"
    if verify_board; then
      log "Hub is up: $HUB_URL/board returns 200."
    else
      die "Hub did not come up — see $REPO_ROOT/logs/hub.log"
    fi
  fi
else
  info "--no-start: skipped launching the hub. Start it later with: npm start"
fi

# ---- 8. Summary -----------------------------------------------------------
printf '\n'
log "Agent Fleet is set up."
cat <<SUMMARY
  Hub URL ........ $HUB_URL    (open this in your browser; auto-open is macOS-only)
  Dashboard ...... $HUB_URL/
  Tokens ......... $ENV_FILE   (join + admin; keep private, never commit)
  MCP config ..... $REPO_ROOT/.mcp.json   (loaded by Claude Code from this clone)
  Hooks .......... $HOOKS_DIR

  Next:
    1) Open $HUB_URL in your browser.
    2) Restart Claude Code so it loads the MCP server + hooks.
    3) In a session: fleet_join with a callsign, then fleet_send a message.

  Multi-node / public dashboard / cockpit terminal are opt-in — see QUICKSTART.md.
SUMMARY
